### autograd(自动求导)
pytorch的核心包是autograd,autograd包提供了tensor自动求导功能。
#### Tensor
    torch.tensor是autograd的核心类，如果将tensor的requires_grad参数设置为True，tensor将会记录所有操作。当计算完成后，tensor调用backward()函数后，会自动计算出tensor的gradient(梯度),并保存到tensor的grad参数下。
    如果需要停止梯度计算的话，调用tensor的detach()函数，从计算图中剥离。另外也可以通过将代码块放在 with torch.no_grad()下，这样代码块中的tensor都不会计算梯度。
    tensor还有一个重要的参数grad_fn。grad_fn是Function函数的实现，每个tensor都有grad_fn，用户创建的tensor的grad_fn为None。
    如果想要计算导数，可以调用tensor的backward()函数，如果tensor是一个标量（scalar)，backward()函数不需要传入任何值；如果tensor包含多个元素，backward()需要设置gradients，参数的size与tensor相同。

In [14]:
import torch

创建tensor，设置requires_grad=True, track它的梯度

In [15]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


操作x， elemtwise加2

In [16]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


由于y是加法操作后的结果，所以y的grad_fn为addBackward.

对y做更多操作，结果如下：

In [17]:
z  = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


可以通过in-place方式修改tensor的requires_grad,创建tensor时，requires_grad默认为False

In [18]:
a = torch.randn(2, 2)
a = (a + 3) / (a - 1)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(b.requires_grad)

False
True
True


#### Gradients(梯度)
通过tensor的backward()计算梯度

In [19]:
out.backward()

获取梯度值

In [21]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
